services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build: ./.docker/php-fpm
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
     - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/db_storage:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9090:80'
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql


